### ISSUE TITLE
Low contrast on 'Subscribe' button

### ISSUE THREAD

**Issue by metamoni** [vue-a11y/vue-a11y.com#2]
The 'Subscribe' button on the vue-a11y homepage is difficult to spot. The contrast between the page's white background and the button's light grey is too low. Here's a [contrast checker](https://webaim.org/resources/contrastchecker/) you can use to improve the contrast ratio.

**Comment by ktquez** [comment]
Hi @metamoni, how are you? 
Thanks for the feedback.

I'm sorry for answering so late. I hadn't seen that problem open.
 
We didn't fix it before, because our idea at the time was to launch a new layout, but some things happened, and we didn't.

Now that the new layout is ready, we fixed these flaws, and if you want to contribute anything to the project, you are very welcome.
